#logging:
#  level:
# Uncomment for logging SQL commands
#    org:
#      hibernate:
#        SQL: DEBUG
# Uncomment for logging SQL request parameters
#        type.descriptor.sql.BasicBinder: TRACE
#        orm.jdbc.bind: TRACE
